# Generated by Django 4.0.3 on 2022-06-18 09:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='nothing-to-show', editable=False, populate_from='user', unique=True),
        ),
    ]
